package com.ublblog.dao;

import com.ublblog.model.ArticleTag;
import com.ublblog.model.ArticleTagExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ArticleTagMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_article_tag
	 * @mbggenerated  Sat Apr 30 17:26:36 CST 2016
	 */
	int countByExample(ArticleTagExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_article_tag
	 * @mbggenerated  Sat Apr 30 17:26:36 CST 2016
	 */
	int deleteByExample(ArticleTagExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_article_tag
	 * @mbggenerated  Sat Apr 30 17:26:36 CST 2016
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_article_tag
	 * @mbggenerated  Sat Apr 30 17:26:36 CST 2016
	 */
	int insert(ArticleTag record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_article_tag
	 * @mbggenerated  Sat Apr 30 17:26:36 CST 2016
	 */
	int insertSelective(ArticleTag record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_article_tag
	 * @mbggenerated  Sat Apr 30 17:26:36 CST 2016
	 */
	List<ArticleTag> selectByExampleWithBLOBs(ArticleTagExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_article_tag
	 * @mbggenerated  Sat Apr 30 17:26:36 CST 2016
	 */
	List<ArticleTag> selectByExample(ArticleTagExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_article_tag
	 * @mbggenerated  Sat Apr 30 17:26:36 CST 2016
	 */
	ArticleTag selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_article_tag
	 * @mbggenerated  Sat Apr 30 17:26:36 CST 2016
	 */
	int updateByExampleSelective(@Param("record") ArticleTag record, @Param("example") ArticleTagExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_article_tag
	 * @mbggenerated  Sat Apr 30 17:26:36 CST 2016
	 */
	int updateByExampleWithBLOBs(@Param("record") ArticleTag record, @Param("example") ArticleTagExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_article_tag
	 * @mbggenerated  Sat Apr 30 17:26:36 CST 2016
	 */
	int updateByExample(@Param("record") ArticleTag record, @Param("example") ArticleTagExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_article_tag
	 * @mbggenerated  Sat Apr 30 17:26:36 CST 2016
	 */
	int updateByPrimaryKeySelective(ArticleTag record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_article_tag
	 * @mbggenerated  Sat Apr 30 17:26:36 CST 2016
	 */
	int updateByPrimaryKeyWithBLOBs(ArticleTag record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_article_tag
	 * @mbggenerated  Sat Apr 30 17:26:36 CST 2016
	 */
	int updateByPrimaryKey(ArticleTag record);
}