package com.ublblog.dao;

import com.ublblog.model.ArticleComment;
import com.ublblog.model.ArticleCommentExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ArticleCommentMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_article_comment
	 * @mbggenerated  Sat Apr 30 17:26:36 CST 2016
	 */
	int countByExample(ArticleCommentExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_article_comment
	 * @mbggenerated  Sat Apr 30 17:26:36 CST 2016
	 */
	int deleteByExample(ArticleCommentExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_article_comment
	 * @mbggenerated  Sat Apr 30 17:26:36 CST 2016
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_article_comment
	 * @mbggenerated  Sat Apr 30 17:26:36 CST 2016
	 */
	int insert(ArticleComment record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_article_comment
	 * @mbggenerated  Sat Apr 30 17:26:36 CST 2016
	 */
	int insertSelective(ArticleComment record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_article_comment
	 * @mbggenerated  Sat Apr 30 17:26:36 CST 2016
	 */
	List<ArticleComment> selectByExampleWithBLOBs(ArticleCommentExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_article_comment
	 * @mbggenerated  Sat Apr 30 17:26:36 CST 2016
	 */
	List<ArticleComment> selectByExample(ArticleCommentExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_article_comment
	 * @mbggenerated  Sat Apr 30 17:26:36 CST 2016
	 */
	ArticleComment selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_article_comment
	 * @mbggenerated  Sat Apr 30 17:26:36 CST 2016
	 */
	int updateByExampleSelective(@Param("record") ArticleComment record,
			@Param("example") ArticleCommentExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_article_comment
	 * @mbggenerated  Sat Apr 30 17:26:36 CST 2016
	 */
	int updateByExampleWithBLOBs(@Param("record") ArticleComment record,
			@Param("example") ArticleCommentExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_article_comment
	 * @mbggenerated  Sat Apr 30 17:26:36 CST 2016
	 */
	int updateByExample(@Param("record") ArticleComment record, @Param("example") ArticleCommentExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_article_comment
	 * @mbggenerated  Sat Apr 30 17:26:36 CST 2016
	 */
	int updateByPrimaryKeySelective(ArticleComment record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_article_comment
	 * @mbggenerated  Sat Apr 30 17:26:36 CST 2016
	 */
	int updateByPrimaryKeyWithBLOBs(ArticleComment record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_article_comment
	 * @mbggenerated  Sat Apr 30 17:26:36 CST 2016
	 */
	int updateByPrimaryKey(ArticleComment record);
}