package com.ublblog.dao;

import com.ublblog.model.ArticleCategory;
import com.ublblog.model.ArticleCategoryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ArticleCategoryMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_article_category
	 * @mbggenerated  Sat Apr 30 17:26:36 CST 2016
	 */
	int countByExample(ArticleCategoryExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_article_category
	 * @mbggenerated  Sat Apr 30 17:26:36 CST 2016
	 */
	int deleteByExample(ArticleCategoryExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_article_category
	 * @mbggenerated  Sat Apr 30 17:26:36 CST 2016
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_article_category
	 * @mbggenerated  Sat Apr 30 17:26:36 CST 2016
	 */
	int insert(ArticleCategory record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_article_category
	 * @mbggenerated  Sat Apr 30 17:26:36 CST 2016
	 */
	int insertSelective(ArticleCategory record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_article_category
	 * @mbggenerated  Sat Apr 30 17:26:36 CST 2016
	 */
	List<ArticleCategory> selectByExampleWithBLOBs(ArticleCategoryExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_article_category
	 * @mbggenerated  Sat Apr 30 17:26:36 CST 2016
	 */
	List<ArticleCategory> selectByExample(ArticleCategoryExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_article_category
	 * @mbggenerated  Sat Apr 30 17:26:36 CST 2016
	 */
	ArticleCategory selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_article_category
	 * @mbggenerated  Sat Apr 30 17:26:36 CST 2016
	 */
	int updateByExampleSelective(@Param("record") ArticleCategory record,
			@Param("example") ArticleCategoryExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_article_category
	 * @mbggenerated  Sat Apr 30 17:26:36 CST 2016
	 */
	int updateByExampleWithBLOBs(@Param("record") ArticleCategory record,
			@Param("example") ArticleCategoryExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_article_category
	 * @mbggenerated  Sat Apr 30 17:26:36 CST 2016
	 */
	int updateByExample(@Param("record") ArticleCategory record, @Param("example") ArticleCategoryExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_article_category
	 * @mbggenerated  Sat Apr 30 17:26:36 CST 2016
	 */
	int updateByPrimaryKeySelective(ArticleCategory record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_article_category
	 * @mbggenerated  Sat Apr 30 17:26:36 CST 2016
	 */
	int updateByPrimaryKeyWithBLOBs(ArticleCategory record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_article_category
	 * @mbggenerated  Sat Apr 30 17:26:36 CST 2016
	 */
	int updateByPrimaryKey(ArticleCategory record);
}