package com.ublblog.dao;

import com.ublblog.model.ExtendPage;
import com.ublblog.model.ExtendPageExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ExtendPageMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_extend_page
	 * @mbggenerated  Sat Apr 30 17:26:36 CST 2016
	 */
	int countByExample(ExtendPageExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_extend_page
	 * @mbggenerated  Sat Apr 30 17:26:36 CST 2016
	 */
	int deleteByExample(ExtendPageExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_extend_page
	 * @mbggenerated  Sat Apr 30 17:26:36 CST 2016
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_extend_page
	 * @mbggenerated  Sat Apr 30 17:26:36 CST 2016
	 */
	int insert(ExtendPage record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_extend_page
	 * @mbggenerated  Sat Apr 30 17:26:36 CST 2016
	 */
	int insertSelective(ExtendPage record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_extend_page
	 * @mbggenerated  Sat Apr 30 17:26:36 CST 2016
	 */
	List<ExtendPage> selectByExampleWithBLOBs(ExtendPageExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_extend_page
	 * @mbggenerated  Sat Apr 30 17:26:36 CST 2016
	 */
	List<ExtendPage> selectByExample(ExtendPageExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_extend_page
	 * @mbggenerated  Sat Apr 30 17:26:36 CST 2016
	 */
	ExtendPage selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_extend_page
	 * @mbggenerated  Sat Apr 30 17:26:36 CST 2016
	 */
	int updateByExampleSelective(@Param("record") ExtendPage record, @Param("example") ExtendPageExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_extend_page
	 * @mbggenerated  Sat Apr 30 17:26:36 CST 2016
	 */
	int updateByExampleWithBLOBs(@Param("record") ExtendPage record, @Param("example") ExtendPageExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_extend_page
	 * @mbggenerated  Sat Apr 30 17:26:36 CST 2016
	 */
	int updateByExample(@Param("record") ExtendPage record, @Param("example") ExtendPageExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_extend_page
	 * @mbggenerated  Sat Apr 30 17:26:36 CST 2016
	 */
	int updateByPrimaryKeySelective(ExtendPage record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_extend_page
	 * @mbggenerated  Sat Apr 30 17:26:36 CST 2016
	 */
	int updateByPrimaryKeyWithBLOBs(ExtendPage record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_extend_page
	 * @mbggenerated  Sat Apr 30 17:26:36 CST 2016
	 */
	int updateByPrimaryKey(ExtendPage record);
}