package com.ublblog.dao;

import com.ublblog.model.FriendlyLink;
import com.ublblog.model.FriendlyLinkExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FriendlyLinkMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_friendly_link
	 * @mbggenerated  Sat Apr 30 17:26:36 CST 2016
	 */
	int countByExample(FriendlyLinkExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_friendly_link
	 * @mbggenerated  Sat Apr 30 17:26:36 CST 2016
	 */
	int deleteByExample(FriendlyLinkExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_friendly_link
	 * @mbggenerated  Sat Apr 30 17:26:36 CST 2016
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_friendly_link
	 * @mbggenerated  Sat Apr 30 17:26:36 CST 2016
	 */
	int insert(FriendlyLink record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_friendly_link
	 * @mbggenerated  Sat Apr 30 17:26:36 CST 2016
	 */
	int insertSelective(FriendlyLink record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_friendly_link
	 * @mbggenerated  Sat Apr 30 17:26:36 CST 2016
	 */
	List<FriendlyLink> selectByExample(FriendlyLinkExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_friendly_link
	 * @mbggenerated  Sat Apr 30 17:26:36 CST 2016
	 */
	FriendlyLink selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_friendly_link
	 * @mbggenerated  Sat Apr 30 17:26:36 CST 2016
	 */
	int updateByExampleSelective(@Param("record") FriendlyLink record, @Param("example") FriendlyLinkExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_friendly_link
	 * @mbggenerated  Sat Apr 30 17:26:36 CST 2016
	 */
	int updateByExample(@Param("record") FriendlyLink record, @Param("example") FriendlyLinkExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_friendly_link
	 * @mbggenerated  Sat Apr 30 17:26:36 CST 2016
	 */
	int updateByPrimaryKeySelective(FriendlyLink record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_friendly_link
	 * @mbggenerated  Sat Apr 30 17:26:36 CST 2016
	 */
	int updateByPrimaryKey(FriendlyLink record);
}