package com.ublblog.dao;

import com.ublblog.model.RelArticleTag;
import com.ublblog.model.RelArticleTagExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RelArticleTagMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rel_article_tag
	 * @mbggenerated  Sat Apr 30 17:26:36 CST 2016
	 */
	int countByExample(RelArticleTagExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rel_article_tag
	 * @mbggenerated  Sat Apr 30 17:26:36 CST 2016
	 */
	int deleteByExample(RelArticleTagExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rel_article_tag
	 * @mbggenerated  Sat Apr 30 17:26:36 CST 2016
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rel_article_tag
	 * @mbggenerated  Sat Apr 30 17:26:36 CST 2016
	 */
	int insert(RelArticleTag record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rel_article_tag
	 * @mbggenerated  Sat Apr 30 17:26:36 CST 2016
	 */
	int insertSelective(RelArticleTag record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rel_article_tag
	 * @mbggenerated  Sat Apr 30 17:26:36 CST 2016
	 */
	List<RelArticleTag> selectByExample(RelArticleTagExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rel_article_tag
	 * @mbggenerated  Sat Apr 30 17:26:36 CST 2016
	 */
	RelArticleTag selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rel_article_tag
	 * @mbggenerated  Sat Apr 30 17:26:36 CST 2016
	 */
	int updateByExampleSelective(@Param("record") RelArticleTag record, @Param("example") RelArticleTagExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rel_article_tag
	 * @mbggenerated  Sat Apr 30 17:26:36 CST 2016
	 */
	int updateByExample(@Param("record") RelArticleTag record, @Param("example") RelArticleTagExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rel_article_tag
	 * @mbggenerated  Sat Apr 30 17:26:36 CST 2016
	 */
	int updateByPrimaryKeySelective(RelArticleTag record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rel_article_tag
	 * @mbggenerated  Sat Apr 30 17:26:36 CST 2016
	 */
	int updateByPrimaryKey(RelArticleTag record);
}