package com.ublblog.model;

import java.util.Date;

public class Article {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_article.id
	 * @mbggenerated  Sat Apr 30 17:26:36 CST 2016
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_article.title
	 * @mbggenerated  Sat Apr 30 17:26:36 CST 2016
	 */
	private String title;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_article.category
	 * @mbggenerated  Sat Apr 30 17:26:36 CST 2016
	 */
	private Integer category;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_article.create_time
	 * @mbggenerated  Sat Apr 30 17:26:36 CST 2016
	 */
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_article.deleted
	 * @mbggenerated  Sat Apr 30 17:26:36 CST 2016
	 */
	private Integer deleted;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_article.read_count
	 * @mbggenerated  Sat Apr 30 17:26:36 CST 2016
	 */
	private Integer readCount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_article.content
	 * @mbggenerated  Sat Apr 30 17:26:36 CST 2016
	 */
	private String content;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_article.id
	 * @return  the value of tb_article.id
	 * @mbggenerated  Sat Apr 30 17:26:36 CST 2016
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_article.id
	 * @param id  the value for tb_article.id
	 * @mbggenerated  Sat Apr 30 17:26:36 CST 2016
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_article.title
	 * @return  the value of tb_article.title
	 * @mbggenerated  Sat Apr 30 17:26:36 CST 2016
	 */
	public String getTitle() {
		return title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_article.title
	 * @param title  the value for tb_article.title
	 * @mbggenerated  Sat Apr 30 17:26:36 CST 2016
	 */
	public void setTitle(String title) {
		this.title = title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_article.category
	 * @return  the value of tb_article.category
	 * @mbggenerated  Sat Apr 30 17:26:36 CST 2016
	 */
	public Integer getCategory() {
		return category;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_article.category
	 * @param category  the value for tb_article.category
	 * @mbggenerated  Sat Apr 30 17:26:36 CST 2016
	 */
	public void setCategory(Integer category) {
		this.category = category;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_article.create_time
	 * @return  the value of tb_article.create_time
	 * @mbggenerated  Sat Apr 30 17:26:36 CST 2016
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_article.create_time
	 * @param createTime  the value for tb_article.create_time
	 * @mbggenerated  Sat Apr 30 17:26:36 CST 2016
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_article.deleted
	 * @return  the value of tb_article.deleted
	 * @mbggenerated  Sat Apr 30 17:26:36 CST 2016
	 */
	public Integer getDeleted() {
		return deleted;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_article.deleted
	 * @param deleted  the value for tb_article.deleted
	 * @mbggenerated  Sat Apr 30 17:26:36 CST 2016
	 */
	public void setDeleted(Integer deleted) {
		this.deleted = deleted;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_article.read_count
	 * @return  the value of tb_article.read_count
	 * @mbggenerated  Sat Apr 30 17:26:36 CST 2016
	 */
	public Integer getReadCount() {
		return readCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_article.read_count
	 * @param readCount  the value for tb_article.read_count
	 * @mbggenerated  Sat Apr 30 17:26:36 CST 2016
	 */
	public void setReadCount(Integer readCount) {
		this.readCount = readCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_article.content
	 * @return  the value of tb_article.content
	 * @mbggenerated  Sat Apr 30 17:26:36 CST 2016
	 */
	public String getContent() {
		return content;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_article.content
	 * @param content  the value for tb_article.content
	 * @mbggenerated  Sat Apr 30 17:26:36 CST 2016
	 */
	public void setContent(String content) {
		this.content = content;
	}
}