package com.ublblog.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ArticleCommentExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table tb_article_comment
	 * @mbggenerated  Sat Apr 30 17:26:36 CST 2016
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table tb_article_comment
	 * @mbggenerated  Sat Apr 30 17:26:36 CST 2016
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table tb_article_comment
	 * @mbggenerated  Sat Apr 30 17:26:36 CST 2016
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_article_comment
	 * @mbggenerated  Sat Apr 30 17:26:36 CST 2016
	 */
	public ArticleCommentExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_article_comment
	 * @mbggenerated  Sat Apr 30 17:26:36 CST 2016
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_article_comment
	 * @mbggenerated  Sat Apr 30 17:26:36 CST 2016
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_article_comment
	 * @mbggenerated  Sat Apr 30 17:26:36 CST 2016
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_article_comment
	 * @mbggenerated  Sat Apr 30 17:26:36 CST 2016
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_article_comment
	 * @mbggenerated  Sat Apr 30 17:26:36 CST 2016
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_article_comment
	 * @mbggenerated  Sat Apr 30 17:26:36 CST 2016
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_article_comment
	 * @mbggenerated  Sat Apr 30 17:26:36 CST 2016
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_article_comment
	 * @mbggenerated  Sat Apr 30 17:26:36 CST 2016
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_article_comment
	 * @mbggenerated  Sat Apr 30 17:26:36 CST 2016
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_article_comment
	 * @mbggenerated  Sat Apr 30 17:26:36 CST 2016
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table tb_article_comment
	 * @mbggenerated  Sat Apr 30 17:26:36 CST 2016
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(Integer value) {
			addCriterion("id =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(Integer value) {
			addCriterion("id <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(Integer value) {
			addCriterion("id >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("id >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(Integer value) {
			addCriterion("id <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(Integer value) {
			addCriterion("id <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<Integer> values) {
			addCriterion("id in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<Integer> values) {
			addCriterion("id not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(Integer value1, Integer value2) {
			addCriterion("id between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(Integer value1, Integer value2) {
			addCriterion("id not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andArticleIdIsNull() {
			addCriterion("article_id is null");
			return (Criteria) this;
		}

		public Criteria andArticleIdIsNotNull() {
			addCriterion("article_id is not null");
			return (Criteria) this;
		}

		public Criteria andArticleIdEqualTo(Integer value) {
			addCriterion("article_id =", value, "articleId");
			return (Criteria) this;
		}

		public Criteria andArticleIdNotEqualTo(Integer value) {
			addCriterion("article_id <>", value, "articleId");
			return (Criteria) this;
		}

		public Criteria andArticleIdGreaterThan(Integer value) {
			addCriterion("article_id >", value, "articleId");
			return (Criteria) this;
		}

		public Criteria andArticleIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("article_id >=", value, "articleId");
			return (Criteria) this;
		}

		public Criteria andArticleIdLessThan(Integer value) {
			addCriterion("article_id <", value, "articleId");
			return (Criteria) this;
		}

		public Criteria andArticleIdLessThanOrEqualTo(Integer value) {
			addCriterion("article_id <=", value, "articleId");
			return (Criteria) this;
		}

		public Criteria andArticleIdIn(List<Integer> values) {
			addCriterion("article_id in", values, "articleId");
			return (Criteria) this;
		}

		public Criteria andArticleIdNotIn(List<Integer> values) {
			addCriterion("article_id not in", values, "articleId");
			return (Criteria) this;
		}

		public Criteria andArticleIdBetween(Integer value1, Integer value2) {
			addCriterion("article_id between", value1, value2, "articleId");
			return (Criteria) this;
		}

		public Criteria andArticleIdNotBetween(Integer value1, Integer value2) {
			addCriterion("article_id not between", value1, value2, "articleId");
			return (Criteria) this;
		}

		public Criteria andUserNameIsNull() {
			addCriterion("user_name is null");
			return (Criteria) this;
		}

		public Criteria andUserNameIsNotNull() {
			addCriterion("user_name is not null");
			return (Criteria) this;
		}

		public Criteria andUserNameEqualTo(String value) {
			addCriterion("user_name =", value, "userName");
			return (Criteria) this;
		}

		public Criteria andUserNameNotEqualTo(String value) {
			addCriterion("user_name <>", value, "userName");
			return (Criteria) this;
		}

		public Criteria andUserNameGreaterThan(String value) {
			addCriterion("user_name >", value, "userName");
			return (Criteria) this;
		}

		public Criteria andUserNameGreaterThanOrEqualTo(String value) {
			addCriterion("user_name >=", value, "userName");
			return (Criteria) this;
		}

		public Criteria andUserNameLessThan(String value) {
			addCriterion("user_name <", value, "userName");
			return (Criteria) this;
		}

		public Criteria andUserNameLessThanOrEqualTo(String value) {
			addCriterion("user_name <=", value, "userName");
			return (Criteria) this;
		}

		public Criteria andUserNameLike(String value) {
			addCriterion("user_name like", value, "userName");
			return (Criteria) this;
		}

		public Criteria andUserNameNotLike(String value) {
			addCriterion("user_name not like", value, "userName");
			return (Criteria) this;
		}

		public Criteria andUserNameIn(List<String> values) {
			addCriterion("user_name in", values, "userName");
			return (Criteria) this;
		}

		public Criteria andUserNameNotIn(List<String> values) {
			addCriterion("user_name not in", values, "userName");
			return (Criteria) this;
		}

		public Criteria andUserNameBetween(String value1, String value2) {
			addCriterion("user_name between", value1, value2, "userName");
			return (Criteria) this;
		}

		public Criteria andUserNameNotBetween(String value1, String value2) {
			addCriterion("user_name not between", value1, value2, "userName");
			return (Criteria) this;
		}

		public Criteria andBlogUrlIsNull() {
			addCriterion("blog_url is null");
			return (Criteria) this;
		}

		public Criteria andBlogUrlIsNotNull() {
			addCriterion("blog_url is not null");
			return (Criteria) this;
		}

		public Criteria andBlogUrlEqualTo(String value) {
			addCriterion("blog_url =", value, "blogUrl");
			return (Criteria) this;
		}

		public Criteria andBlogUrlNotEqualTo(String value) {
			addCriterion("blog_url <>", value, "blogUrl");
			return (Criteria) this;
		}

		public Criteria andBlogUrlGreaterThan(String value) {
			addCriterion("blog_url >", value, "blogUrl");
			return (Criteria) this;
		}

		public Criteria andBlogUrlGreaterThanOrEqualTo(String value) {
			addCriterion("blog_url >=", value, "blogUrl");
			return (Criteria) this;
		}

		public Criteria andBlogUrlLessThan(String value) {
			addCriterion("blog_url <", value, "blogUrl");
			return (Criteria) this;
		}

		public Criteria andBlogUrlLessThanOrEqualTo(String value) {
			addCriterion("blog_url <=", value, "blogUrl");
			return (Criteria) this;
		}

		public Criteria andBlogUrlLike(String value) {
			addCriterion("blog_url like", value, "blogUrl");
			return (Criteria) this;
		}

		public Criteria andBlogUrlNotLike(String value) {
			addCriterion("blog_url not like", value, "blogUrl");
			return (Criteria) this;
		}

		public Criteria andBlogUrlIn(List<String> values) {
			addCriterion("blog_url in", values, "blogUrl");
			return (Criteria) this;
		}

		public Criteria andBlogUrlNotIn(List<String> values) {
			addCriterion("blog_url not in", values, "blogUrl");
			return (Criteria) this;
		}

		public Criteria andBlogUrlBetween(String value1, String value2) {
			addCriterion("blog_url between", value1, value2, "blogUrl");
			return (Criteria) this;
		}

		public Criteria andBlogUrlNotBetween(String value1, String value2) {
			addCriterion("blog_url not between", value1, value2, "blogUrl");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIsNull() {
			addCriterion("create_time is null");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIsNotNull() {
			addCriterion("create_time is not null");
			return (Criteria) this;
		}

		public Criteria andCreateTimeEqualTo(Date value) {
			addCriterion("create_time =", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotEqualTo(Date value) {
			addCriterion("create_time <>", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeGreaterThan(Date value) {
			addCriterion("create_time >", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("create_time >=", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeLessThan(Date value) {
			addCriterion("create_time <", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
			addCriterion("create_time <=", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIn(List<Date> values) {
			addCriterion("create_time in", values, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotIn(List<Date> values) {
			addCriterion("create_time not in", values, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeBetween(Date value1, Date value2) {
			addCriterion("create_time between", value1, value2, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
			addCriterion("create_time not between", value1, value2, "createTime");
			return (Criteria) this;
		}

		public Criteria andEmailIsNull() {
			addCriterion("email is null");
			return (Criteria) this;
		}

		public Criteria andEmailIsNotNull() {
			addCriterion("email is not null");
			return (Criteria) this;
		}

		public Criteria andEmailEqualTo(String value) {
			addCriterion("email =", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailNotEqualTo(String value) {
			addCriterion("email <>", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailGreaterThan(String value) {
			addCriterion("email >", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailGreaterThanOrEqualTo(String value) {
			addCriterion("email >=", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailLessThan(String value) {
			addCriterion("email <", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailLessThanOrEqualTo(String value) {
			addCriterion("email <=", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailLike(String value) {
			addCriterion("email like", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailNotLike(String value) {
			addCriterion("email not like", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailIn(List<String> values) {
			addCriterion("email in", values, "email");
			return (Criteria) this;
		}

		public Criteria andEmailNotIn(List<String> values) {
			addCriterion("email not in", values, "email");
			return (Criteria) this;
		}

		public Criteria andEmailBetween(String value1, String value2) {
			addCriterion("email between", value1, value2, "email");
			return (Criteria) this;
		}

		public Criteria andEmailNotBetween(String value1, String value2) {
			addCriterion("email not between", value1, value2, "email");
			return (Criteria) this;
		}

		public Criteria andFatherCommIsNull() {
			addCriterion("father_comm is null");
			return (Criteria) this;
		}

		public Criteria andFatherCommIsNotNull() {
			addCriterion("father_comm is not null");
			return (Criteria) this;
		}

		public Criteria andFatherCommEqualTo(Integer value) {
			addCriterion("father_comm =", value, "fatherComm");
			return (Criteria) this;
		}

		public Criteria andFatherCommNotEqualTo(Integer value) {
			addCriterion("father_comm <>", value, "fatherComm");
			return (Criteria) this;
		}

		public Criteria andFatherCommGreaterThan(Integer value) {
			addCriterion("father_comm >", value, "fatherComm");
			return (Criteria) this;
		}

		public Criteria andFatherCommGreaterThanOrEqualTo(Integer value) {
			addCriterion("father_comm >=", value, "fatherComm");
			return (Criteria) this;
		}

		public Criteria andFatherCommLessThan(Integer value) {
			addCriterion("father_comm <", value, "fatherComm");
			return (Criteria) this;
		}

		public Criteria andFatherCommLessThanOrEqualTo(Integer value) {
			addCriterion("father_comm <=", value, "fatherComm");
			return (Criteria) this;
		}

		public Criteria andFatherCommIn(List<Integer> values) {
			addCriterion("father_comm in", values, "fatherComm");
			return (Criteria) this;
		}

		public Criteria andFatherCommNotIn(List<Integer> values) {
			addCriterion("father_comm not in", values, "fatherComm");
			return (Criteria) this;
		}

		public Criteria andFatherCommBetween(Integer value1, Integer value2) {
			addCriterion("father_comm between", value1, value2, "fatherComm");
			return (Criteria) this;
		}

		public Criteria andFatherCommNotBetween(Integer value1, Integer value2) {
			addCriterion("father_comm not between", value1, value2, "fatherComm");
			return (Criteria) this;
		}

		public Criteria andBeFeedbackIsNull() {
			addCriterion("be_feedback is null");
			return (Criteria) this;
		}

		public Criteria andBeFeedbackIsNotNull() {
			addCriterion("be_feedback is not null");
			return (Criteria) this;
		}

		public Criteria andBeFeedbackEqualTo(String value) {
			addCriterion("be_feedback =", value, "beFeedback");
			return (Criteria) this;
		}

		public Criteria andBeFeedbackNotEqualTo(String value) {
			addCriterion("be_feedback <>", value, "beFeedback");
			return (Criteria) this;
		}

		public Criteria andBeFeedbackGreaterThan(String value) {
			addCriterion("be_feedback >", value, "beFeedback");
			return (Criteria) this;
		}

		public Criteria andBeFeedbackGreaterThanOrEqualTo(String value) {
			addCriterion("be_feedback >=", value, "beFeedback");
			return (Criteria) this;
		}

		public Criteria andBeFeedbackLessThan(String value) {
			addCriterion("be_feedback <", value, "beFeedback");
			return (Criteria) this;
		}

		public Criteria andBeFeedbackLessThanOrEqualTo(String value) {
			addCriterion("be_feedback <=", value, "beFeedback");
			return (Criteria) this;
		}

		public Criteria andBeFeedbackLike(String value) {
			addCriterion("be_feedback like", value, "beFeedback");
			return (Criteria) this;
		}

		public Criteria andBeFeedbackNotLike(String value) {
			addCriterion("be_feedback not like", value, "beFeedback");
			return (Criteria) this;
		}

		public Criteria andBeFeedbackIn(List<String> values) {
			addCriterion("be_feedback in", values, "beFeedback");
			return (Criteria) this;
		}

		public Criteria andBeFeedbackNotIn(List<String> values) {
			addCriterion("be_feedback not in", values, "beFeedback");
			return (Criteria) this;
		}

		public Criteria andBeFeedbackBetween(String value1, String value2) {
			addCriterion("be_feedback between", value1, value2, "beFeedback");
			return (Criteria) this;
		}

		public Criteria andBeFeedbackNotBetween(String value1, String value2) {
			addCriterion("be_feedback not between", value1, value2, "beFeedback");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table tb_article_comment
	 * @mbggenerated  Sat Apr 30 17:26:36 CST 2016
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tb_article_comment
     *
     * @mbggenerated do_not_delete_during_merge Thu Apr 28 20:46:34 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}