package com.ublblog.model;

public class ArticleCategory {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_article_category.id
	 * @mbggenerated  Sat Apr 30 17:26:36 CST 2016
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_article_category.name
	 * @mbggenerated  Sat Apr 30 17:26:36 CST 2016
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_article_category.sort
	 * @mbggenerated  Sat Apr 30 17:26:36 CST 2016
	 */
	private Integer sort;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_article_category.description
	 * @mbggenerated  Sat Apr 30 17:26:36 CST 2016
	 */
	private String description;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_article_category.id
	 * @return  the value of tb_article_category.id
	 * @mbggenerated  Sat Apr 30 17:26:36 CST 2016
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_article_category.id
	 * @param id  the value for tb_article_category.id
	 * @mbggenerated  Sat Apr 30 17:26:36 CST 2016
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_article_category.name
	 * @return  the value of tb_article_category.name
	 * @mbggenerated  Sat Apr 30 17:26:36 CST 2016
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_article_category.name
	 * @param name  the value for tb_article_category.name
	 * @mbggenerated  Sat Apr 30 17:26:36 CST 2016
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_article_category.sort
	 * @return  the value of tb_article_category.sort
	 * @mbggenerated  Sat Apr 30 17:26:36 CST 2016
	 */
	public Integer getSort() {
		return sort;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_article_category.sort
	 * @param sort  the value for tb_article_category.sort
	 * @mbggenerated  Sat Apr 30 17:26:36 CST 2016
	 */
	public void setSort(Integer sort) {
		this.sort = sort;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_article_category.description
	 * @return  the value of tb_article_category.description
	 * @mbggenerated  Sat Apr 30 17:26:36 CST 2016
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_article_category.description
	 * @param description  the value for tb_article_category.description
	 * @mbggenerated  Sat Apr 30 17:26:36 CST 2016
	 */
	public void setDescription(String description) {
		this.description = description;
	}
}