package com.ublblog.model;

import java.util.Date;

public class ArticleComment {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_article_comment.id
	 * @mbggenerated  Sat Apr 30 17:26:36 CST 2016
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_article_comment.article_id
	 * @mbggenerated  Sat Apr 30 17:26:36 CST 2016
	 */
	private Integer articleId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_article_comment.user_name
	 * @mbggenerated  Sat Apr 30 17:26:36 CST 2016
	 */
	private String userName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_article_comment.blog_url
	 * @mbggenerated  Sat Apr 30 17:26:36 CST 2016
	 */
	private String blogUrl;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_article_comment.create_time
	 * @mbggenerated  Sat Apr 30 17:26:36 CST 2016
	 */
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_article_comment.email
	 * @mbggenerated  Sat Apr 30 17:26:36 CST 2016
	 */
	private String email;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_article_comment.father_comm
	 * @mbggenerated  Sat Apr 30 17:26:36 CST 2016
	 */
	private Integer fatherComm;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_article_comment.be_feedback
	 * @mbggenerated  Sat Apr 30 17:26:36 CST 2016
	 */
	private String beFeedback;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_article_comment.content
	 * @mbggenerated  Sat Apr 30 17:26:36 CST 2016
	 */
	private String content;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_article_comment.id
	 * @return  the value of tb_article_comment.id
	 * @mbggenerated  Sat Apr 30 17:26:36 CST 2016
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_article_comment.id
	 * @param id  the value for tb_article_comment.id
	 * @mbggenerated  Sat Apr 30 17:26:36 CST 2016
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_article_comment.article_id
	 * @return  the value of tb_article_comment.article_id
	 * @mbggenerated  Sat Apr 30 17:26:36 CST 2016
	 */
	public Integer getArticleId() {
		return articleId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_article_comment.article_id
	 * @param articleId  the value for tb_article_comment.article_id
	 * @mbggenerated  Sat Apr 30 17:26:36 CST 2016
	 */
	public void setArticleId(Integer articleId) {
		this.articleId = articleId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_article_comment.user_name
	 * @return  the value of tb_article_comment.user_name
	 * @mbggenerated  Sat Apr 30 17:26:36 CST 2016
	 */
	public String getUserName() {
		return userName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_article_comment.user_name
	 * @param userName  the value for tb_article_comment.user_name
	 * @mbggenerated  Sat Apr 30 17:26:36 CST 2016
	 */
	public void setUserName(String userName) {
		this.userName = userName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_article_comment.blog_url
	 * @return  the value of tb_article_comment.blog_url
	 * @mbggenerated  Sat Apr 30 17:26:36 CST 2016
	 */
	public String getBlogUrl() {
		return blogUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_article_comment.blog_url
	 * @param blogUrl  the value for tb_article_comment.blog_url
	 * @mbggenerated  Sat Apr 30 17:26:36 CST 2016
	 */
	public void setBlogUrl(String blogUrl) {
		this.blogUrl = blogUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_article_comment.create_time
	 * @return  the value of tb_article_comment.create_time
	 * @mbggenerated  Sat Apr 30 17:26:36 CST 2016
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_article_comment.create_time
	 * @param createTime  the value for tb_article_comment.create_time
	 * @mbggenerated  Sat Apr 30 17:26:36 CST 2016
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_article_comment.email
	 * @return  the value of tb_article_comment.email
	 * @mbggenerated  Sat Apr 30 17:26:36 CST 2016
	 */
	public String getEmail() {
		return email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_article_comment.email
	 * @param email  the value for tb_article_comment.email
	 * @mbggenerated  Sat Apr 30 17:26:36 CST 2016
	 */
	public void setEmail(String email) {
		this.email = email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_article_comment.father_comm
	 * @return  the value of tb_article_comment.father_comm
	 * @mbggenerated  Sat Apr 30 17:26:36 CST 2016
	 */
	public Integer getFatherComm() {
		return fatherComm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_article_comment.father_comm
	 * @param fatherComm  the value for tb_article_comment.father_comm
	 * @mbggenerated  Sat Apr 30 17:26:36 CST 2016
	 */
	public void setFatherComm(Integer fatherComm) {
		this.fatherComm = fatherComm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_article_comment.be_feedback
	 * @return  the value of tb_article_comment.be_feedback
	 * @mbggenerated  Sat Apr 30 17:26:36 CST 2016
	 */
	public String getBeFeedback() {
		return beFeedback;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_article_comment.be_feedback
	 * @param beFeedback  the value for tb_article_comment.be_feedback
	 * @mbggenerated  Sat Apr 30 17:26:36 CST 2016
	 */
	public void setBeFeedback(String beFeedback) {
		this.beFeedback = beFeedback;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_article_comment.content
	 * @return  the value of tb_article_comment.content
	 * @mbggenerated  Sat Apr 30 17:26:36 CST 2016
	 */
	public String getContent() {
		return content;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_article_comment.content
	 * @param content  the value for tb_article_comment.content
	 * @mbggenerated  Sat Apr 30 17:26:36 CST 2016
	 */
	public void setContent(String content) {
		this.content = content;
	}
}