package com.ublblog.model;

public class ExtendPage {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_extend_page.id
	 * @mbggenerated  Sat Apr 30 17:26:36 CST 2016
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_extend_page.url
	 * @mbggenerated  Sat Apr 30 17:26:36 CST 2016
	 */
	private String url;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_extend_page.name
	 * @mbggenerated  Sat Apr 30 17:26:36 CST 2016
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_extend_page.display
	 * @mbggenerated  Sat Apr 30 17:26:36 CST 2016
	 */
	private Integer display;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_extend_page.page_content
	 * @mbggenerated  Sat Apr 30 17:26:36 CST 2016
	 */
	private String pageContent;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_extend_page.id
	 * @return  the value of tb_extend_page.id
	 * @mbggenerated  Sat Apr 30 17:26:36 CST 2016
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_extend_page.id
	 * @param id  the value for tb_extend_page.id
	 * @mbggenerated  Sat Apr 30 17:26:36 CST 2016
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_extend_page.url
	 * @return  the value of tb_extend_page.url
	 * @mbggenerated  Sat Apr 30 17:26:36 CST 2016
	 */
	public String getUrl() {
		return url;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_extend_page.url
	 * @param url  the value for tb_extend_page.url
	 * @mbggenerated  Sat Apr 30 17:26:36 CST 2016
	 */
	public void setUrl(String url) {
		this.url = url;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_extend_page.name
	 * @return  the value of tb_extend_page.name
	 * @mbggenerated  Sat Apr 30 17:26:36 CST 2016
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_extend_page.name
	 * @param name  the value for tb_extend_page.name
	 * @mbggenerated  Sat Apr 30 17:26:36 CST 2016
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_extend_page.display
	 * @return  the value of tb_extend_page.display
	 * @mbggenerated  Sat Apr 30 17:26:36 CST 2016
	 */
	public Integer getDisplay() {
		return display;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_extend_page.display
	 * @param display  the value for tb_extend_page.display
	 * @mbggenerated  Sat Apr 30 17:26:36 CST 2016
	 */
	public void setDisplay(Integer display) {
		this.display = display;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_extend_page.page_content
	 * @return  the value of tb_extend_page.page_content
	 * @mbggenerated  Sat Apr 30 17:26:36 CST 2016
	 */
	public String getPageContent() {
		return pageContent;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_extend_page.page_content
	 * @param pageContent  the value for tb_extend_page.page_content
	 * @mbggenerated  Sat Apr 30 17:26:36 CST 2016
	 */
	public void setPageContent(String pageContent) {
		this.pageContent = pageContent;
	}
}