package com.ublblog.model;

public class FriendlyLink {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_friendly_link.id
	 * @mbggenerated  Sat Apr 30 17:26:36 CST 2016
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_friendly_link.name
	 * @mbggenerated  Sat Apr 30 17:26:36 CST 2016
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_friendly_link.link
	 * @mbggenerated  Sat Apr 30 17:26:36 CST 2016
	 */
	private String link;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_friendly_link.id
	 * @return  the value of tb_friendly_link.id
	 * @mbggenerated  Sat Apr 30 17:26:36 CST 2016
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_friendly_link.id
	 * @param id  the value for tb_friendly_link.id
	 * @mbggenerated  Sat Apr 30 17:26:36 CST 2016
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_friendly_link.name
	 * @return  the value of tb_friendly_link.name
	 * @mbggenerated  Sat Apr 30 17:26:36 CST 2016
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_friendly_link.name
	 * @param name  the value for tb_friendly_link.name
	 * @mbggenerated  Sat Apr 30 17:26:36 CST 2016
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_friendly_link.link
	 * @return  the value of tb_friendly_link.link
	 * @mbggenerated  Sat Apr 30 17:26:36 CST 2016
	 */
	public String getLink() {
		return link;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_friendly_link.link
	 * @param link  the value for tb_friendly_link.link
	 * @mbggenerated  Sat Apr 30 17:26:36 CST 2016
	 */
	public void setLink(String link) {
		this.link = link;
	}
}