package com.ublblog.model;

public class RelArticleTag {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rel_article_tag.id
	 * @mbggenerated  Sat Apr 30 17:26:36 CST 2016
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rel_article_tag.article_id
	 * @mbggenerated  Sat Apr 30 17:26:36 CST 2016
	 */
	private Integer articleId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rel_article_tag.tag_id
	 * @mbggenerated  Sat Apr 30 17:26:36 CST 2016
	 */
	private Integer tagId;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rel_article_tag.id
	 * @return  the value of rel_article_tag.id
	 * @mbggenerated  Sat Apr 30 17:26:36 CST 2016
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rel_article_tag.id
	 * @param id  the value for rel_article_tag.id
	 * @mbggenerated  Sat Apr 30 17:26:36 CST 2016
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rel_article_tag.article_id
	 * @return  the value of rel_article_tag.article_id
	 * @mbggenerated  Sat Apr 30 17:26:36 CST 2016
	 */
	public Integer getArticleId() {
		return articleId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rel_article_tag.article_id
	 * @param articleId  the value for rel_article_tag.article_id
	 * @mbggenerated  Sat Apr 30 17:26:36 CST 2016
	 */
	public void setArticleId(Integer articleId) {
		this.articleId = articleId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rel_article_tag.tag_id
	 * @return  the value of rel_article_tag.tag_id
	 * @mbggenerated  Sat Apr 30 17:26:36 CST 2016
	 */
	public Integer getTagId() {
		return tagId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rel_article_tag.tag_id
	 * @param tagId  the value for rel_article_tag.tag_id
	 * @mbggenerated  Sat Apr 30 17:26:36 CST 2016
	 */
	public void setTagId(Integer tagId) {
		this.tagId = tagId;
	}
}