package com.ublblog.model;

public class UserWithBLOBs extends User {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_user.description
	 * @mbggenerated  Sat Apr 30 17:26:36 CST 2016
	 */
	private String description;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_user.image
	 * @mbggenerated  Sat Apr 30 17:26:36 CST 2016
	 */
	private String image;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_user.description
	 * @return  the value of tb_user.description
	 * @mbggenerated  Sat Apr 30 17:26:36 CST 2016
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_user.description
	 * @param description  the value for tb_user.description
	 * @mbggenerated  Sat Apr 30 17:26:36 CST 2016
	 */
	public void setDescription(String description) {
		this.description = description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_user.image
	 * @return  the value of tb_user.image
	 * @mbggenerated  Sat Apr 30 17:26:36 CST 2016
	 */
	public String getImage() {
		return image;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_user.image
	 * @param image  the value for tb_user.image
	 * @mbggenerated  Sat Apr 30 17:26:36 CST 2016
	 */
	public void setImage(String image) {
		this.image = image;
	}
}