package com.ublblog.model;

public class User {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_user.id
	 * @mbggenerated  Sat Apr 30 17:26:36 CST 2016
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_user.name
	 * @mbggenerated  Sat Apr 30 17:26:36 CST 2016
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_user.password
	 * @mbggenerated  Sat Apr 30 17:26:36 CST 2016
	 */
	private String password;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_user.show_name
	 * @mbggenerated  Sat Apr 30 17:26:36 CST 2016
	 */
	private String showName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_user.email
	 * @mbggenerated  Sat Apr 30 17:26:36 CST 2016
	 */
	private String email;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_user.id
	 * @return  the value of tb_user.id
	 * @mbggenerated  Sat Apr 30 17:26:36 CST 2016
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_user.id
	 * @param id  the value for tb_user.id
	 * @mbggenerated  Sat Apr 30 17:26:36 CST 2016
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_user.name
	 * @return  the value of tb_user.name
	 * @mbggenerated  Sat Apr 30 17:26:36 CST 2016
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_user.name
	 * @param name  the value for tb_user.name
	 * @mbggenerated  Sat Apr 30 17:26:36 CST 2016
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_user.password
	 * @return  the value of tb_user.password
	 * @mbggenerated  Sat Apr 30 17:26:36 CST 2016
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_user.password
	 * @param password  the value for tb_user.password
	 * @mbggenerated  Sat Apr 30 17:26:36 CST 2016
	 */
	public void setPassword(String password) {
		this.password = password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_user.show_name
	 * @return  the value of tb_user.show_name
	 * @mbggenerated  Sat Apr 30 17:26:36 CST 2016
	 */
	public String getShowName() {
		return showName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_user.show_name
	 * @param showName  the value for tb_user.show_name
	 * @mbggenerated  Sat Apr 30 17:26:36 CST 2016
	 */
	public void setShowName(String showName) {
		this.showName = showName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_user.email
	 * @return  the value of tb_user.email
	 * @mbggenerated  Sat Apr 30 17:26:36 CST 2016
	 */
	public String getEmail() {
		return email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_user.email
	 * @param email  the value for tb_user.email
	 * @mbggenerated  Sat Apr 30 17:26:36 CST 2016
	 */
	public void setEmail(String email) {
		this.email = email;
	}
}